### ISSUE TITLE
Cannot build on macos Ventura

### ISSUE THREAD

**Issue by bentxt** [fujita-y/ypsilon#168]
If I try to follow the tutorial and build on macos Ventura 13.

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cmake --install .
```

I get the error like
```
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Release
CMake Error at CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake
```

**Comment by fujita-y** [comment]
Hi bentxt, Thank you for reporting issue. I've successfully reproduce the issue and working on fix!

**Comment by fujita-y** [comment]
Ypsilon has updated to support LLVM 15 which is a default version of homebrew.
I've confirmed following commands succesfuly install Ypsilon to Mac OS 13 Ventura.

```
# Install LLVM 15
brew update
brew install llvm
echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc

# Install Ypsilon
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cmake --install .
```

Thanks!

**Comment by bentxt** [comment]
thanks, it works now. Maybe as an improvement the path to $LLVM/bin could be set manually, instead of messing with $PATH
